services:
  web:
    build: .
    container_name: auto-laboratory-container
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: temporary-secret-key-for-learning
      DJANGO_ALLOWED_HOSTS: 127.0.0.1,localhost
