[pytest]
DJANGO_SETTINGS_MODULE = config.settings
pythonpath = django_app

testpaths =
    playwright_tests
    django_tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    --tracing=retain-on-failure
    --strict-markers